In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
from collections import Counter
print(os.listdir("./input"))

['data.csv']

In [6]:
data = pd.read_csv('./input/data.csv')
data.head(5)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
0,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015
1,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015
2,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015
3,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015
4,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015

In [7]:
len(data)

1890

# Предобработка датасета

In [8]:
answer_ls = [] # создадим список с ответами. сюда будем добавлять ответы по мере прохождения теста
# сюда можем вписать создание новых колонок в датасете

# 1. У какого фильма из списка самый большой бюджет?
Варианты ответов:
1. The Dark Knight Rises (tt1345836)
2. Spider-Man 3 (tt0413300)
3. Avengers: Age of Ultron (tt2395427)
4. The Warrior's Way	(tt1032751)
5. Pirates of the Caribbean: On Stranger Tides (tt1298650)

In [16]:
# тут вводим ваш ответ и добавлем в его список ответов (сейчас для примера стоит "1")
data[data.budget == data.budget.max()]
answer_ls.append(4)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
491,tt1032751,0.25054,425000000,11087569,The Warrior's Way,Kate Bosworth|Jang Dong-gun|Geoffrey Rush|Dann...,Sngmoo Lee,Assassin. Hero. Legend.,An Asian assassin (Dong-gun Jang) is forced to...,100,Adventure|Fantasy|Action|Western|Thriller,Boram Entertainment Inc.,12/2/2010,74,6.4,2010

# 2. Какой из фильмов самый длительный (в минутах)
1. The Lord of the Rings: The Return of the King	(tt0167260)
2. Gods and Generals	(tt0279111)
3. King Kong	(tt0360717)
4. Pearl Harbor	(tt0213149)
5. Alexander	(tt0346491)

In [21]:
display(data[data.runtime == data.runtime.max()])

answer_ls.append(2)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
1158,tt0279111,0.469518,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,214,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,23,5.8,2003

# 3. Какой из фильмов самый короткий (в минутах)
Варианты ответов:

1. Home on the Range	tt0299172
2. The Jungle Book 2	tt0283426
3. Winnie the Pooh	tt1449283
4. Corpse Bride	tt0121164
5. Hoodwinked!	tt0443536

In [25]:
display(data[data.runtime == data.runtime.min()])

answer_ls.append(3)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
769,tt1449283,1.425344,30000000,14460000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",63,Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,4/13/2011,174,6.8,2011

# 4. Средняя длительность фильма?

Варианты ответов:
1. 115
2. 110
3. 105
4. 120
5. 100

In [30]:
display(data.runtime.mean())
display(data.runtime.sum() / len(data.runtime))
answer_ls.append(2)

106.5

109.65343915343915

109.65343915343915

# 5. Средняя длительность фильма по медиане?
Варианты ответов:
1. 106
2. 112
3. 101
4. 120
5. 115

In [32]:
display(data.runtime.median())
answer_ls.append(1)

106.5

# 6. Какой самый прибыльный фильм?
Варианты ответов:
1. The Avengers	tt0848228
2. Minions	tt2293640
3. Star Wars: The Force Awakens	tt2488496
4. Furious 7	tt2820852
5. Avatar	tt0499549

In [36]:
#data['income'] = data.revenue - data.budget
display(data[data.income == data.income.max()])
answer_ls.append(5)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,income
239,tt0499549,9.432768,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,8458,7.1,2009,2544505847

# 7. Какой фильм самый убыточный?
Варианты ответов:
1. Supernova tt0134983
2. The Warrior's Way tt1032751
3. Flushed Away	tt0424095
4. The Adventures of Pluto Nash	tt0180052
5. The Lone Ranger	tt1210819

In [38]:
display(data[data.income == data.income.min()])
answer_ls.append(2)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,income
491,tt1032751,0.25054,425000000,11087569,The Warrior's Way,Kate Bosworth|Jang Dong-gun|Geoffrey Rush|Dann...,Sngmoo Lee,Assassin. Hero. Legend.,An Asian assassin (Dong-gun Jang) is forced to...,100,Adventure|Fantasy|Action|Western|Thriller,Boram Entertainment Inc.,12/2/2010,74,6.4,2010,-413912431

# 8. Сколько всего фильмов в прибыли?
Варианты ответов:
1. 1478
2. 1520
3. 1241
4. 1135
5. 1398

In [41]:
data[data.income > 0].count()
answer_ls.append(1)

# 9. Самый прибыльный фильм в 2008 году?
Варианты ответов:
1. Madagascar: Escape 2 Africa	tt0479952
2. Iron Man	tt0371746
3. Kung Fu Panda	tt0441773
4. The Dark Knight	tt0468569
5. Mamma Mia!	tt0795421

In [53]:
data[(data.release_year == 2008)].sort_values(['revenue'], ascending=False)
answer_ls.append(4)

# 10. Самый убыточный фильм за период с 2012 по 2014 (включительно)?
Варианты ответов:
1. Winter's Tale	tt1837709
2. Stolen	tt1656186
3. Broken City	tt1235522
4. Upside Down	tt1374992
5. The Lone Ranger	tt1210819

In [55]:
data[(data.release_year >= 2012) & (data.release_year <= 2014)].sort_values(['income'])
answer_ls.append(5)

# 11. Какого жанра фильмов больше всего?
Варианты ответов:
1. Action
2. Adventure
3. Drama
4. Comedy
5. Thriller

In [65]:
dict_genres = {}
for genres in data.genres:
    list_genre = genres.split('|')
    for genre in list_genre:
        if genre in dict_genres.keys():
            dict_genres[genre] += 1
        else:
            dict_genres[genre] = 1
dict_genres

{'Action': 583,
 'Adventure': 416,
 'Science Fiction': 248,
 'Thriller': 597,
 'Fantasy': 223,
 'Crime': 315,
 'Western': 20,
 'Drama': 782,
 'Family': 260,
 'Animation': 139,
 'Comedy': 683,
 'Mystery': 168,
 'Romance': 308,
 'War': 58,
 'History': 62,
 'Music': 64,
 'Horror': 176,
 'Documentary': 8,
 'Foreign': 2}

In [66]:
answer_ls.append(3)

# 12. Какого жанра среди прибыльных фильмов больше всего?
Варианты ответов:
1. Drama
2. Comedy
3. Action
4. Thriller
5. Adventure

In [69]:
data[data.income > 0]
dict_genres = {}
for genres in data[data.income > 0].genres:
    list_genre = genres.split('|')
    for genre in list_genre:
        if genre in dict_genres.keys():
            dict_genres[genre] += 1
        else:
            dict_genres[genre] = 1
print (dict_genres)
answer_ls.append(1)

{'Action': 444, 'Adventure': 337, 'Science Fiction': 195, 'Thriller': 446, 'Fantasy': 188, 'Crime': 231, 'Western': 12, 'Drama': 560, 'Family': 226, 'Animation': 120, 'Comedy': 551, 'Mystery': 119, 'Romance': 242, 'War': 41, 'History': 46, 'Music': 47, 'Horror': 150, 'Documentary': 7}

# 13. Кто из режиссеров снял больше всего фильмов?
Варианты ответов:
1. Steven Spielberg
2. Ridley Scott 
3. Steven Soderbergh
4. Christopher Nolan
5. Clint Eastwood

In [72]:
data.director.value_counts()
answer_ls.append(3)

# 14. Кто из режиссеров снял больше всего Прибыльных фильмов?
Варианты ответов:
1. Steven Soderbergh
2. Clint Eastwood
3. Steven Spielberg
4. Ridley Scott
5. Christopher Nolan

In [74]:
data[data.income > 0].director.value_counts()
answer_ls.append(4)

# 15. Кто из режиссеров принес больше всего прибыли?
Варианты ответов:
1. Steven Spielberg
2. Christopher Nolan
3. David Yates
4. James Cameron
5. Peter Jackson

In [88]:
dir_income = pd.DataFrame()
dir_income['Steven Spielberg'] = [data[data.director == 'Steven Spielberg'].income.sum()]
dir_income['Christopher Nolan'] = [data[data.director == 'Christopher Nolan'].income.sum()]
dir_income['David Yates'] = [data[data.director == 'David Yates'].income.sum()]
dir_income['James Cameron'] = [data[data.director == 'James Cameron'].income.sum()]
dir_income['Peter Jackson'] = [data[data.director == 'Peter Jackson'].income.sum()]
display(dir_income)
display(dir_income.sort_values(0, axis = 1))
answer_ls.append(5)

,Steven Spielberg,Christopher Nolan,David Yates,James Cameron,Peter Jackson
0,2449700791,3162548502,3379295625,2548546718,5202593685

,Steven Spielberg,James Cameron,Christopher Nolan,David Yates,Peter Jackson
0,2449700791,2548546718,3162548502,3379295625,5202593685

# 16. Какой актер принес больше всего прибыли?
Варианты ответов:
1. Emma Watson
2. Johnny Depp
3. Michelle Rodriguez
4. Orlando Bloom
5. Rupert Grint

In [104]:
dict_actors = {'Emma Watson': [0], 'Johnny Depp': [0], 'Michelle Rodriguez': [0], 'Orlando Bloom': [0], 'Rupert Grint': [0]}
actors_income = pd.DataFrame(dict_actors, columns=['Emma Watson', 'Johnny Depp', 'Michelle Rodriguez', 'Orlando Bloom', 'Rupert Grint'])
actors_income
for index, movie in data.iterrows():    
    for name in actors_income.columns:
        if name in movie['cast']:
            actors_income[name] += movie.income
actors_income.sort_values(0, axis=1)
answer_ls.append(1)

# 17. Какой актер принес меньше всего прибыли в 2012 году?
Варианты ответов:
1. Nicolas Cage
2. Danny Huston
3. Kirsten Dunst
4. Jim Sturgess
5. Sami Gayle

In [113]:
dict_actors = {'Nicolas Cage': [0], 'Danny Huston': [0], 'Kirsten Dunst': [0], 'Jim Sturgess': [0], 'Sami Gayle': [0]}
actors_income = pd.DataFrame(dict_actors, columns=['Nicolas Cage', 'Danny Huston', 'Kirsten Dunst', 'Jim Sturgess', 'Sami Gayle'])
actors_income
for index, movie in data[data.release_year == 2012].iterrows():    
    for name in actors_income.columns:
        if name in movie['cast']:
            actors_income[name] += movie.income
actors_income.sort_values(0, axis=1)
answer_ls.append(3)

# 18. Какой актер снялся в большем количестве высокобюджетных фильмов? (в фильмах где бюджет выше среднего по данной выборке)
Варианты ответов:
1. Tom Cruise
2. Mark Wahlberg 
3. Matt Damon
4. Angelina Jolie
5. Adam Sandler

In [139]:
#data['cast_sep'] = data['cast'].str.split('|')
dict_actors = {}
for index, movie in data[data.budget > data.budget.mean()].iterrows():
    for name in movie.cast_sep:
        if name in dict_actors.keys():
            dict_actors[name] += 1
        else:
            dict_actors[name] = 1
sorted_d = sorted(dict_actors.items(), key=lambda x: x[1], reverse=True)
sorted_d
answer_ls.append(3)

# 19. В фильмах какого жанра больше всего снимался Nicolas Cage?  
Варианты ответа:
1. Drama
2. Action
3. Thriller
4. Adventure
5. Crime

In [160]:
dict_genres = {}
list_genres = data[data['cast'].str.contains(pat='Nicolas Cage') == True].genres.str.split('|')
for genres in list_genres:
    for genre in genres:
        if genre in dict_genres.keys():
            dict_genres[genre] += 1
        else:
            dict_genres[genre] = 1
sorted(dict_genres.items(), key=lambda x: x[1], reverse=True)
answer_ls.append(2)

# 20. Какая студия сняла больше всего фильмов?
Варианты ответа:
1. Universal Pictures (Universal)
2. Paramount Pictures
3. Columbia Pictures
4. Warner Bros
5. Twentieth Century Fox Film Corporation

In [169]:
dict_studios = {}
for index, studios in data.iterrows():
    list_studios = studios['production_companies'].split('|')
    for studio in list_studios:
        if studio in dict_studios.keys():
            dict_studios[studio] += 1
        else:
            dict_studios[studio] = 1
sorted(dict_studios.items(), key=lambda x: x[1], reverse=True)
answer_ls.append(1)

# 21. Какая студия сняла больше всего фильмов в 2015 году?
Варианты ответа:
1. Universal Pictures
2. Paramount Pictures
3. Columbia Pictures
4. Warner Bros
5. Twentieth Century Fox Film Corporation

In [173]:
dict_studios = {}
for index, studios in data[data.release_year == 2015].iterrows():
    list_studios = studios['production_companies'].split('|')
    for studio in list_studios:
        if studio in dict_studios.keys():
            dict_studios[studio] += 1
        else:
            dict_studios[studio] = 1
sorted(dict_studios.items(), key=lambda x: x[1], reverse=True)
answer_ls.append(4)

# 22. Какая студия заработала больше всего денег в жанре комедий за все время?
Варианты ответа:
1. Warner Bros
2. Universal Pictures (Universal)
3. Columbia Pictures
4. Paramount Pictures
5. Walt Disney

In [177]:
dict_studios = {}
for index, studios in data[data.genres.str.contains(pat='Comedy')].iterrows():
    movie_income = studios['income']
    list_studios = studios['production_companies'].split('|')
    for studio in list_studios:
        if studio in dict_studios.keys():
            dict_studios[studio] += movie_income
        else:
            dict_studios[studio] = movie_income
print(sorted(dict_studios.items(), key=lambda x: x[1], reverse=True))
answer_ls.append(2)

[('Universal Pictures', 8961545581), ('Walt Disney Pictures', 7669710326), ('Twentieth Century Fox Film Corporation', 5686960294), ('Columbia Pictures', 5646343696), ('DreamWorks Animation', 4789049764), ('Pixar Animation Studios', 4232507237), ('Warner Bros.', 3894922770), ('New Line Cinema', 3259242692), ('DreamWorks SKG', 3143226857), ('Paramount Pictures', 3055625722), ('Relativity Media', 3036733344), ('Twentieth Century Fox Animation', 3030806037), ('Blue Sky Studios', 3024335014), ('Village Roadshow Pictures', 2383194524), ('Happy Madison Productions', 2196445292), ('Illumination Entertainment', 1977492847), ('Columbia Pictures Corporation', 1817280373), ('Regency Enterprises', 1766412563), ('Dune Entertainment', 1703149736), ('Pacific Data Images (PDI)', 1699136912), ('Sony Pictures Animation', 1686288994), ('Fox 2000 Pictures', 1673413405), ('Apatow Productions', 1419417727), ('21 Laps Entertainment', 1262425642), ('Dimension Films', 1235565030), ('Walt Disney Animation Studios', 1142430016), ('Green Hat Films', 1092507501), ('Legendary Pictures', 1056237337), ('Touchstone Pictures', 1019666722), ('Metro-Goldwyn-Mayer (MGM)', 1005610791), ('Spyglass Entertainment', 971077188), ('Working Title Films', 947760501), ('Amblin Entertainment', 901906115), ('Media Rights Capital', 885155837), ('Mosaic Media Group', 875646074), ('1492 Pictures', 872091430), ('Miramax Films', 870409935), ('Nickelodeon Movies', 830553839), ('Fox Searchlight Pictures', 813485630), ('Revolution Studios', 762936184), ('TSG Entertainment', 761041830), ('Everyman Pictures', 719159797), ('Gold Circle Films', 710871179), ('Original Film', 701365254), ('Kerner Entertainment Company', 696183501), ('Walt Disney Studios Motion Pictures', 678708609), ('Dune Entertainment III', 675931563), ('Bagdasarian Productions', 669506638), ('The Weinstein Company', 653932716), ('Fuzzy Door Productions', 647231921), ('Tribeca Productions', 645636958), ('Hemisphere Media Capital', 641460954), ('Red Granite Pictures', 612198096), ('Gary Sanchez Productions', 594586861), ('Waverly Films', 589565765), ('Studio Canal', 574982363), ('Good Universe', 574316238), ('Parkes/MacDonald Productions', 558444031), ('Internationale Filmproduktion Richter', 557841637), ('Playtone', 557841637), ('Littlestar', 557841637), ('Ingenious Film Partners', 547565770), ('Home Box Office (HBO)', 538600478), ('Imagenation Abu Dhabi FZ', 530203109), ('Mandate Pictures', 528266720), ('Brad Grey Pictures', 527913666), ('Flower Films (II)', 524265840), ('Silver Pictures', 519867028), ('Davis Entertainment', 517206491), ('20th Century Fox', 515090337), ('Gold/Miller Productions', 496638967), ('Summit Entertainment', 487439123), ('Sony Pictures Entertainment (SPE)', 482764187), ('The Zanuck Company', 480959741), ('Weed Road Pictures', 478476270), ('Scott Rudin Productions', 473608359), ('StudioCanal', 469894140), ('Wayans Bros. Entertainment', 468922045), ('Zide-Perry Productions', 467377949), ('Wigram Productions', 467173788), ('Mad Hatter Entertainment', 464123048), ('Warner Bros. Animation', 463037717), ('Tim Burton Productions', 462986980), ('Tapestry Films', 444916367), ('New Regency Pictures', 441364154), ('Castle Rock Entertainment', 440970624), ('Imagine Entertainment', 435291822), ('Plan B Entertainment', 430315269), ('Marc Platt Productions', 425196863), ('IFP Westcoast Erste', 424270619), ('Chernin Entertainment', 422949865), ('Lin Pictures', 422573485), ('Internationale Filmproduktion Blackbird Dritte', 421956747), ('Shady Acres Entertainment', 418077844), ('Vertigo Entertainment', 409160692), ('Pit Bull Productions', 404572835), ('DC Comics', 401856991), ('Storyline Entertainment', 392149234), ('Media Magik Entertainment', 378058113), ('Point Grey Pictures', 371594718), ('Playtone Productions', 369904419), ('Dutch Oven', 368207520), ('New Regency Productions', 368207520), ('Screen Gems', 367745195), ('MPH Entertainment', 363744044), ('Overbrook Entertainment', 359663968), ('Atlas Entertainment', 359652423), ('Brownstone Productions', 356856620), ('Gracie Films', 355779125), ('Platinum Dunes', 352200000), ('Darren Star Productions', 350252786), ('Red Hour Films', 345469304), ('Jerry Bruckheimer Films', 341328095), ('Josephson Entertainment', 335978832), ('Robert Simonds Productions', 329089130), ('Mandeville Films', 323553619), ('Marv Films', 322802136), ('Cloudy Productions', 322802136), ('Wild West Picture Show Productions', 321690887), ('Avery Pix', 321011297), ('Feigco Entertainment', 317899332), ('Aardman Animations', 316085073), ('Major Studio Partners', 314560763), ('Tiger Aspect Productions', 309736344), ('Centropolis Entertainment', 304111707), ('Wind Dancer Productions', 304111707), ('Parkes+MacDonald Image Nation', 301818803), ('Focus Features', 299412300), ('Paramount Animation', 298601627), ('Icon Entertainment International', 295997141), ('MTV Films', 294293135), ('Appian Way', 292000694), ('EMJAG Productions', 292000694), ('Sikelia Productions', 292000694), ('Peninsula Films', 291551094), ('Stuber Productions', 289851496), ('Karz Entertainment', 287464773), ('Kennedy Miller Productions', 284335608), ('Kingdom Feature Productions', 284335608), ('Animal Logic', 284335608), ('Sony Pictures Releasing', 279046309), ('Kurtzman/Orci', 277375031), ('Gunn Films', 276534523), ('De Line Pictures', 276083286), ('Nancy Tenenbaum Films', 275444045), ('Sunswept Entertainment', 272114902), ('Dentsu', 263809199), ('Museum Canada Productions', 263106170), ('BBC Films', 262661625), ('Producers Circle', 261776732), ('BenderSpink', 260701935), ('Conundrum Entertainment', 260460622), ('Rat Entertainment', 257949145), ('Liveplanet', 257553595), ('Little Bird', 256929795), ('Andalasia Productions', 255487652), ('Right Coast Productions', 255487652), ('Rainforest Films', 249571010), ('Four By Two Productions', 243572744), ('NeoReel', 242434178), ("Eric's Boy", 233633907), ('Team Todd', 233633907), ('Moving Pictures', 233633907), ('Gratitude International', 233633907), ('Walt Disney Feature Animation', 227711813), ('Walden Media', 226403025), ('Broken Road Productions', 225810289), ('Fortis Films', 225460460), ('Sony Pictures Entertainment', 222949060), ('Moving Picture Company (MPC)', 222424282), ('Olive Bridge Entertainment', 218938754), ('Big Screen Productions', 213807502), ('TF1 Films Production', 211101452), ('Mike Zoss Productions', 211091218), ('Dreamworks Pictures', 210650585), ('DNA Films', 210112895), ('Indian Paintbrush', 208691114), ('Canal+', 206810296), ('The Montecito Picture Company', 204648705), ('Buena Vista', 204435555), ('Heyday Films', 204207227), ('Alcon Entertainment', 202608219), ('CBS Films', 195330353), ('Cube Vision', 194916482), ('Jersey Films', 191344937), ('Mayhem Pictures', 190343051), ('HBO Films', 188347692), ('GK Films', 185251752), ('WideAwake', 184002198), ('Ingenious Media', 180255887), ('PathÃ©', 179834564), ('Three Strange Angels', 179389434), ('Lakeshore Entertainment', 178081787), ('LivePlanet', 176449203), ('Loumolo & Co.', 176449203), ('Living Films', 174455986), ('Wonderland Sound and Vision', 174204422), ('Tall Trees Productions', 173091676), ('Sony', 170384621), ('Escape Artists', 170110493), ('LStar Capital', 166194717), ('Rice Films', 164485654), ('NPV Entertainment', 163708324), ('Type A Films', 163648539), ('Lucamar Productions', 162902372), ('Nick Wechsler Productions', 160221571), ('Extension 765', 160221571), ('Stephen J. Cannell Productions', 159585328), ('Mad Chance', 157492969), ('Ad Hominem Enterprises', 157243185), ('LBI Productions', 156781193), ('Heyday films', 155990978), ('Spring Creek Productions', 152179800), ('DreamWorks Pictures', 148840295), ('Mediastream Vierte Film GmbH & Co. Vermarktungs KG', 147722310), ('Katalyst Films', 145940403), ('Tree Line Films', 144930431), ('Pink Machine', 144930431), ('Studio Babelsberg', 143484950), ('Don Simpson/Jerry Bruckheimer Films', 143339556), ('Whamaphram Productions', 142817841), ('Montecito Picture Company, The', 141156732), ('Aggregate Films', 138965010), ('DumbDumb', 138965010), ('Cannell Studios', 138441614), ('Columbus 81 Productions', 137594577), ('Internationale Filmproduktion Blackswan', 137259441), ('RatPac-Dune Entertainment', 137008072), ('Dickhouse Productions', 136831537), ('Penn Station Entertainment', 135000000), ('Guy Walks into a Bar Productions', 132048597), ('Zadan / Meron Productions', 130372502), ('Loofah Productions', 129963386), ('BrownHouse Productions', 128335153), ('Bottom of the Ninth Productions', 128335153), ('David Brown Productions', 127500343), ('Fat Free', 127500343), ('Anonymous Content', 126400244), ('Offspring Entertainment', 126313322), ('Monkey Dance Productions', 125880543), ('WV Films III', 125404726), ('Reliance BIG Entertainment', 125205105), ('Miramax', 124722341), ('Troublemaker Studios', 124262079), ('Participant Media', 123603420), ('Bona Fide Productions', 123353788), ('Rhythm and Hues', 121584141), ('Picnic Basket', 121584141), ('Out of the Blue... Entertainment', 121269535), ("It's a Laugh Productions", 120545279), ('Millar Gough Ink', 120545279), ('Genre Films', 119621271), ('France 3 CinÃ©ma', 118432856), ('La Petite Reine', 118432856), ('Studio 37', 118432856), ('uFilm', 118432856), ('Jouror Productions', 118432856), ('Two Ton Films', 117191850), ('Cold Spring Pictures', 114185685), ('Lionsgate', 113731553), ('Color Force', 112117892), ('Kumar Mobiliengesellschaft mbH & Co. Projekt Nr. 1 KG', 111749918), ('Blind Wink', 110724603), ('AR-TL', 110268750), ('Callahan Filmworks', 108320568), ('Iron Horse Entertainment (II)', 107613057), ('Outlaw Sinema', 106402450), ('Gidden Media', 106402450), ('Reserve Room', 105896422), ('Fuji Television Network', 105795793), ('Arts Council of England', 105000000), ('Kramer & Sigman Films', 103862963), ('Zaftig Films', 103862963), ('Laurence Mark Productions', 102440359), ('JC 23 Entertainment', 102026112), ('Lions Gate Films', 101866560), ('DisneyToon Studios', 101165787), ('Prana Studios', 101165787), ('Prana Animation Studios', 101165787), ('Management 360', 100901559), ('Hughes Entertainment', 99906693), ('Shoelace Productions', 99906693), ('Cruella Productions', 98611771), ('Firm Films', 98259062), ('Samuel Goldwyn Films', 98133322), ('Misher Films', 98018522), ('Yucaipa Films', 98018522), ('Hyde Park Films', 97309464), ('Internationale Filmproduktion Stella-del-Sud Second', 96072649), ('Epsilon Motion Pictures', 95517678), ('Laika Entertainment', 95395169), ('Goldcrest Pictures', 94676893), ('Michael London Productions', 93502303), ('Sideways Productions Inc.', 93502303), ('Radar Pictures', 92872192), ('Big Beach Films', 92523181), ('Doom Buggy Productions', 92290266), ('Scholastic Entertainment', 92170815), ('Newmarket Capital Group', 90845033), ('Lawrence Bender Productions', 90845033), ('Pistolero Productions LLC', 90845033), ('Deep River Productions', 88909141), ('Harbour Pictures', 86542059), ('Goldmann Pictures', 86533366), ('Worldview Entertainment', 85215094), ('Le Grisbi Productions', 85215094), ('M Productions', 85215094), ('Studio Mir', 84070507), ('Ott Medien', 83733697), ('TriStar Pictures', 83683480), ('Mediastream Dritte Film GmbH & Co. Beteiligungs KG', 83564935), ('Gulfstream Pictures', 83494610), ('Perdido Productions', 79505481), ('Image Entertainment', 77930623), ('Sony Pictures Home Entertainment', 77597242), ('Ruby Films', 77544580), ('Essential Media & Entertainment', 77544580), ('Hopscotch Features', 77544580), ('Kaplan/Perrone Entertainment', 76431368), ('MMCB Film Produktion 2004', 76431368), ('Gone North Productions', 76086475), ('Storefront Pictures', 75607899), ('Little Stranger', 75011053), ('Infinitum Nihil', 74527149), ('Phoenix Pictures', 74007224), ('Bedford Falls Productions', 72820008), ('Jim Henson Company, The', 72654149), ('David Dobkin Productions', 71222537), ('Emmett/Furla Films', 70940411), ('Envision Entertainment Corporation', 70940411), ('LBI Entertainment', 70081841), ('Village Roadshow Pictures Asia', 67610124), ('Universal Studios', 67364881), ('Gerber Pictures', 65710936), ('Junction Entertainment', 65283742), ('ImageMovers', 65175006), ('Nine Yards Productions', 65071651), ('Rational Packaging Company', 65071651), ('Twentieth Century Fox', 64462508), ('Internationale Filmproduktion Stella-del-SÃ¼d', 64380927), ('Intellectual Properties Worldwide', 62681893), ('Beacon Communications', 62449929), ('Imagi Animation Studios', 61608995), ('Mirage Studios', 61608995), ('Imagi Production', 61608995), ('Kumar Mobiliengesellschaft mbH & Co. Projekt Nr. 2 KG', 61556420), ('Virgin Produced', 61504660), ('Vidhu Vinod Chopra Productions', 61000000), ('Alphaville Productions', 59940815), ('Constantin Film Produktion', 59877553), ('Intermedia Films', 59728529), ('Dee Gee Entertainment', 59728529), ('Prufrock Pictures', 59728529), ('Thirteen Productions', 59455697), ('Atmosphere Entertainment MM', 59188165), ('Chako Film Company', 59188165), ('American Empirical Pictures', 58734189), ('Big Talk Productions', 57552050), ('Impact Pictures', 57274484), ('Nouvelles Ã‰ditions de Films (NEF)', 57274484), ('New Legacy', 57274484), ('Paul Schiff Productions', 56890346), ('Universal Cartoon Studios', 55936232), ('Likely Story', 55464861), ('Exclusive Media Group', 55464861), ('Sycamore Pictures', 55464861), ('Crescendo Productions', 55397508), ('Reel FX Creative Studios', 55000000), ('Universal', 54625195), ('Hammer & Tongs', 54478416), ('Vinyl Films', 54366750), ('RatPac Entertainment', 53895377), ('Dylan Sellers Productions', 53886904), ('Dimension Films (US version)', 53488889), ('Watermark', 53222734), ('Moonrise', 52263166), ('View Askew Productions', 51781648), ('The Collective Studios', 51615414), ('Max Stronghold Productions Inc.', 51369815), ('Wessler Entertainment', 51258289), ('Gaylord Films', 51067909), ('Bernard Gayle Productions', 50636986), ('Neal H. Moritz Productions', 50468332), ('Simon Fields Productions', 49516304), ('Jean Doumanian Productions', 49188937), ('Playtone Production', 49181539), ('Scion Films', 48991867), ('Headline Pictures', 48520298), ('Black & White Productions', 48197993), ('Clifford Werber Productions', 48187984), ('Saturn Films', 47328019), ('Red Wagon Entertainment', 46426169), ('Bewitched', 46426169), ('Alta Loma Entertainment', 45442940), ('MacDonald/Parkes Productions', 44854431), ('Smoke House', 44729358), ('Participant Productions', 44000410), ('Jon Shestack Productions', 43377859), ('Tim Burton Animation Company', 42491068), ('KirchMedia', 42383208), ('Double Feature Films', 42226116), ('Nina Saxon Film Design', 42226116), ('Goldenlight Films', 41837234), ('The Tyler Perry Company', 40072596), ('What to Expect Productions', 39700000), ('Failure to Launch Productions', 38715192), ('Birnbaum / Barber Productions', 38323487), ('Jackie Chan Films Limited', 38323487), ('All Knight Productions', 38323487), ('Fireworks Pictures', 37498534), ('Alphaville Films', 37498534), ('Clinica Estetico', 37126501), ('Screen Gems, Inc.', 36502684), ('Kanbar Entertainment', 36053787), ('Blue Yonder Films', 36053787), ('Bac Films', 35742101), ('Five Roses', 35742101), ('Morgan Creek Productions', 35676058), ('26 Films', 35630314), ('TriStar Productions', 35387687), ('SkyLand Entertainment', 35065672), ('Vast Entertainment', 35028634), ('Open Road Films', 34967935), ('Aldamisa Entertainment', 34967935), ('Kilburn Media', 34967935), ('Fetisov Teterin Films', 34967935), ('Ilion Animation Studios', 34945765), ('Hand Made Films', 34945765), ('Rainmaker Entertainment', 34597643), ('Mainframe Entertainment', 34597643), ('Weinstein Company, The', 34597643), ('Underground', 34307224), ('3 Arts Entertainment', 33915888), ('Michaels-Goldwyn', 33833449), ('Red Hour Productions', 32780981), ('Section Eight', 32358388), ('Stage 6 Films', 31110610), ('Sony Pictures Worldwide Acquisitions (SPWA)', 31110610), ('TDJ Enterprises / New Dimensions Entertainment', 31110610), ('Our Stories Films', 31110610), ('Echo Films', 30830607), ('Disney', 30383113), ('Mosaic', 29779728), ('New Crime Productions', 28572262), ('Smokehouse Pictures', 28191198), ('Parabolic Pictures', 28050886), ('Wildwood Enterprises', 27991087), ('Route One Films', 27991087), ('FilmColony', 27738099), ('Banter', 27280250), ('O.N.C. Entertainment', 27028752), ('Greenestreet Films', 26438988), ('Witness Protection Films', 26438988), ('Konrad Pictures', 25696770), ('Wild Ocean Films', 24901913), ('2S Films', 24901913), ('United Artists', 24349727), ('Groundswell Productions', 23994790), ('Stoller Global Solutions', 23909751), ('Big Kid Pictures', 23450437), ('Runteldat Entertainment', 23424428), ('Aversano Films', 23159963), ('Landscape Entertainment', 23009669), ('John US Productions', 23009669), ('Entertainment Films', 23000000), ('Material Entertainment', 23000000), ('Beech Hill Films', 23000000), ('Artisan Entertainment', 21861859), ('Tyler Perry Company, The', 21609243), ('Blueprint Pictures', 21424799), ('Tollin/Robbins Productions', 21367498), ('Edmonds Entertainment Group (EEG)', 21010817), ('Epidemic Pictures', 21010817), ('The Safran Company', 21010817), ('Wildgaze Films', 20451307), ('Alan Greenspan Productions', 20451307), ('Mars Media Beteiligungs', 20451307), ('Dr D Studios', 20406466), ('Kennedy Miller Mitchell', 20406466), ('Universal Animation Studios', 19834815), ('Sony Pictures', 19809911), ('Closest to the Hole Productions', 19263404), ('Bird and a Bear Entertainment', 19179516), ('Hallway Pictures', 19179516), ('Catch Productions', 19179516), ('Native Pictures Productions', 19155435), ('Bad Robot', 18785180), ('Room 9 Entertainment', 18293509), ('Bungalow Productions', 18288674), ('Silver Lion Films', 18288674), ('Vision View Entertainment', 18288674), ('Blue Askew', 18105111), ('Treehouse Pictures', 18049082), ('Reforma Films', 17316267), ('Spy Next Door', 17236543), ('GreeneStreet Films', 17095657), ('Twins Financing', 17002538), ('Pacific Standard', 16680201), ('New Wave Entertainment', 16620508), ('Terra Firma Films', 16620508), ('Superfinger Entertainment', 16620508), ('EuropaCorp', 16156226), ('Depth of Field', 14287964), ('Alloy Entertainment', 14053061), ('Sneak Preview Productions', 13956509), ('Beverly Detroit', 13801173), ('Propaganda Films', 13801173), ('Intermedia', 13801173), ('Di Bonaventura Pictures', 13664962), ('DC Entertainment', 13664962), ('Element Pictures', 13560274), ('Irish Film Board', 13560274), ('Jaffe / Braunstein Enterprise', 13424826), ('Wintergreen Productions', 13412793), ('Lynda Obst Productions', 13412793), ('Mile High Productions', 12886719), ('Kevin Messick Productions', 12886719), ('Beacon Pictures', 12886719), ('New Upstairs Productions', 12881056), ('Upstairs Canada Productions', 12881056), ('JLT Productions', 12609995), ('Oops Doughnuts Productions', 12005248), ('Frontier Pictures', 12005248), ('DiNovi Pictures', 11478061), ('Overnight Films', 11327899), ('Boxing Cat Films', 11112916), ('Denver and Delilah Productions', 10939027), ('Octagon Films', 10922472), ('Birnbaum/Barber', 10922472), ('Contrafilm', 10426096), ('Hungry Eye Lowland Pictures B.V.', 8856124), ('Flan de Coco Films', 8856124), ('GHS Productions KG', 8222729), ('Munich Film Partners & Company (MFP) GHS Productions', 8222729), ('Nides/McCormick Productions', 8222729), ('Prescience', 7909461), ('40 Acres & A Mule Filmworks', 7728118), ('This Is That Productions', 7664377), ('Land Films Inc.', 7500000), ('Scott Free Productions', 7064105), ('Triple Threat Talent', 7036004), ('Canal Plus', 6894225), ('Grive Productions', 6894225), ('Vendome Pictures', 6160375), ('Provident Films', 5429707), ('Pure Flix Entertainment', 5429707), ('Affirm Films', 5429707), ('FourBoys Entertainment', 5429707), ('Daybreak', 5411183), ('Exodus Film Group', 5000000), ('Exodus Productions', 5000000), ('Sidney Kimmel Entertainment', 4558098), ('British Film Institute (BFI)', 4422261), ('Furry Vengeance Productions', 4340177), ('Sherazade Film Development', 3569964), ('Corduroy Films', 3569964), ('Mark

# 23. Какая студия заработала больше всего денег в 2012 году?
Варианты ответа:
1. Universal Pictures (Universal)
2. Warner Bros
3. Columbia Pictures
4. Paramount Pictures
5. Lucasfilm

In [179]:
dict_studios = {}
for index, studios in data[data.release_year == 2012].iterrows():
    movie_income = studios['income']
    list_studios = studios['production_companies'].split('|')
    for studio in list_studios:
        if studio in dict_studios.keys():
            dict_studios[studio] += movie_income
        else:
            dict_studios[studio] = movie_income
print(sorted(dict_studios.items(), key=lambda x: x[1], reverse=True))
answer_ls.append(3)

[('Columbia Pictures', 2501406608), ('Universal Pictures', 1981011579), ('Marvel Studios', 1299557910), ('Warner Bros.', 1258020056), ('Relativity Media', 1032593938), ('New Line Cinema', 1028114941), ('Metro-Goldwyn-Mayer (MGM)', 1010869947), ('Legendary Pictures', 982041287), ('Summit Entertainment', 961582873), ('Dune Entertainment', 892186707), ('DC Entertainment', 831041287), ('Syncopy', 831041287), ('Blue Sky Studios', 782244782), ('Twentieth Century Fox Animation', 782244782), ('WingNut Films', 767003568), ('DreamWorks Animation', 763862944), ('Twentieth Century Fox Film Corporation', 726676825), ('Lionsgate', 709309876), ('Sunswept Entertainment', 709000000), ('Temple Hill Entertainment', 709000000), ('Color Force', 616210692), ('Fox 2000 Pictures', 544128741), ('Laura Ziskin Productions', 537215857), ('Marvel Entertainment', 537215857), ('The Weinstein Company', 534041592), ('Media Rights Capital', 499368315), ('Fuzzy Door Productions', 499368315), ('Ingenious Film Partners', 489016565), ('Ingenious Media', 489016565), ('Big Screen Productions', 489016565), ('Walt Disney Pictures', 420613375), ('Paramount Pictures', 410726715), ('Amblin Entertainment', 399026776), ('Media Magik Entertainment', 399026776), ('Hemisphere Media Capital', 399026776), ('Parkes/MacDonald Productions', 399026776), ('Imagenation Abu Dhabi FZ', 392165564), ('CAMERON MACKINTOSH', 380809770), ('Walden Media', 371464992), ('Working Title Films', 365528985), ('Pixar Animation Studios', 353983207), ('EuropaCorp', 343345336), ('Sony Pictures Animation', 331713964), ('M6 Films', 331141306), ('Grive Productions', 331141306), ('Canal+', 327129654), ('Screen Gems', 312585077), ('Walt Disney Animation Studios', 306222889), ('Dentsu', 293558894), ('GK Films', 283351277), ('Illumination Entertainment', 278840316), ('Scott Free Productions', 273170142), ('Brandywine Productions', 273170142), ('Contrafilm', 256499543), ('Roth Films', 226600000), ('Bluegrass Films', 217101690), ('Davis-Films', 207462051), ('Smokehouse Pictures', 187824128), ('Tim Burton Productions', 181283356), ('Nu Image Films', 179679980), ('Millennium Films', 179679980), ('Spyglass Entertainment', 166114570), ('Nick Wechsler Productions', 160221571), ('Extension 765', 160221571), ('Original Film', 159585328), ('Stephen J. Cannell Productions', 159585328), ('Mutual Film Company', 158340595), ('Skydance Productions', 158340595), ('TC Productions', 158340595), ('Thunder Road Pictures', 151000000), ('Cott Productions', 151000000), ('Furia de Titanes II, A.I.E.', 151000000), ('Kennedy/Marshall Company, The', 146572938), ('Captivate Entertainment', 146572938), ('Annapurna Pictures', 139685821), ('Telecinco Cinema', 138274123), ('Apaches Entertainment', 138274123), ('Canal+ EspaÃ±a', 138274123), ('Instituto de la CinematografÃ\xada y de las Artes Audiovisuales (ICAA)', 138274123), ('Blumhouse Productions', 137817992), ('Room 101', 137817992), ('Solana Films', 137817992), ('Davis Entertainment', 130000000), ('Adam Schroeder Productions', 130000000), ('Yucaipa Films', 125695102), ('Hammer Film Productions', 110730736), ('UK Film Council', 110730736), ('Alliance Films', 110730736), ('Film i VÃ¤st', 110730736), ('Talisman Productions', 110730736), ('Brownstone Productions', 98350426), ('Misher Films', 98018522), ('Goldmann Pictures', 98018522), ('Rat Entertainment', 98018522), ('Village Roadshow Pictures', 95527149), ('Infinitum Nihil', 95527149), ('20th Century Fox', 94772232), ('Chernin Entertainment', 94772232), ('Hasbro', 94025485), ('Film 44', 94025485), ('First Light Production', 92820716), ('Silver Pictures', 88000000), ('Green Hat Films', 88000000), ('Mandate Pictures', 84281051), ('Escape Artists', 84281051), ('Management 360', 84281051), ('Rainforest Films', 84070507), ('Studio Mir', 84070507), ('Ghost House Pictures', 71446075), ('North Box Productions', 71446075), ('Bandito Brothers', 69272766), ('Apatow Productions', 66128471), ('Sketch Films', 62400000), ('UW4 Productions', 62400000), ('Lakeshore Entertainment', 59293721), ('Aardman Animations', 58338361), ('Scott Rudin Productions', 52263166), ('Indian Paintbrush', 52263166), ('American Empirical Pictures', 52263166), ('Moonrise', 52263166), ('Phoenix Pictures', 50337469), ('Headline Pictures', 48520298), ('Laika Entertainment', 47139399), ('Bazelevs Production', 43265139), ('Abraham Productions', 43265139), ('Location Gourmet', 43265139), ('Tim Burton Animation Company', 42491068), ('Emmett/Furla Films', 41126384), ('Hedge Fund Film Partners', 41126384), ('Crave Films', 41126384), ('Knightsbridge Entertainment', 41126384), ('Focus Features', 40278187), ('Alcon Entertainment', 39700000), ('What to Expect Productions', 39700000), ('Leverage Management', 38100000), ('Closest to the Hole Productions', 38100000), ('Mutant Enemy Productions', 36486080), ('Exclusive Media Group', 34554432), ('Konami Corporation Ltd.', 32302796), ('StudioCanal', 30727492), ('Anarchos Productions', 28482868), ('X-Filme Creative Pool', 28482868), ('Ascension Pictures', 28482868), ('ARD Degeto Film', 28482868), ('Cloud Atlas Productions', 28482868), ('Benaroya Pictures', 27676580), ('Pie Films Inc.', 27676580), ('Wessler Entertainment', 24819301), ('Stoller Global Solutions', 23909751), ('Artina Films', 23485056), ('Lucky Monkey Pictures', 23485056), ('Green Room Films', 23485056), ('Treehouse Pictures', 23485056), ('Plan B Entertainment', 22930465), ('1984 Private Defense Contractors', 22930465), ('Inferno Entertainment', 22930465), ('Chockstone Pictures', 22930465), ('Imagine Entertainment', 20726956), ('MTV Films', 20726956), ('Insurge Pictures', 20726956), ('Mr. Mudd Production', 20400000), ('Endgame Entertainment', 17042000), ('DMG Entertainment', 17042000), ('Ram Bergman Productions', 17042000), ('CinÃ©+', 12204030), ('CBS Films', 11653722), ('Saturn Films', 11550834), ('TriStar Pictures', 10637469), ('Stage 6 Films', 10637469), ('Akil Production Company', 10637469), ('Irish Film Board', 10372606), ('Lawrence Bender Productions', 10346186), ('Automatik Entertainment', 10346186), ('Trigger Street Productions', 10346186), ('87Eleven', 10346186), ('Serenade Films', 7231461), ('Also Known As Pictures', 7231461), ('Blueprint Pictures', 4422261), ('British Film Institute (BFI)', 4422261), ('Film4', 4422261), ('Di Bonaventura Picture', 4221189), ('Dimension Films', 3493728), ('Mark Canton Productions', 3493728), ('Intellectual Properties Worldwide', 3493728), ('Ixtlan', 2000000), ('Onda Entertainment', 2000000), ('IM Global', 1383928), ('Dos Corazones', -2377154), ('Nickelodeon Movies', -2582638), ('Fake Empire', -2582638), ('Sidney Kimmel Entertainment', -3106279), ('Intrepid Pictures', -3136417), ('Film Rites', -3136417), ('Galavis Film', -3136417), ('Picture Machine', -3136417), ('FilmDistrict', -3151217), ('Touchstone Pictures', -3565222), ('Ghoulardi Film Company', -3741940), ('Pariah Entertainment Group', -3916401), ('Liddell Entertainment', -6571952), ('LD Entertainment', -6571952), ('Wonderful Films PLC', -6571952), ('Participant Media', -6861212), ('Media Farm', -6861212), ('Sunday Night', -6861212), ('Dark Castle Entertainment', -7372508), ('Studio Babelsberg Motion Pictures', -7372508), ('Lucasfilm Ltd.', -7634623), ('Partnership Pictures', -7634623), ('DNA Films', -8962258), ('Reliance BIG Entertainment', -8962258), ('Rena Film', -8962258), ('Peach Trees', -8962258), ('A Hot Dog', -10840066), ('Happy Madison Productions', -11941633), ('TÃ©lÃ©film Canada', -14436444), ('Rai Cinema', -14436444), ('Prospero Pictures', -14436444), ('Alfama Films', -14436444), ('Industry Entertainment', -15363831), ('Grindstone Entertainment Group', -15363831), ('Cheetah Vision', -15363831), ('Mandalay Vision', -15363831), ('Paradox Entertainment', -15363831), ('Corner Store Entertainment', -15581387), ('American Zoetrope', -16215682), ('VideoFilmes', -16215682), ('Vanguard Films', -16215682), ('Anonymous Content', -17863423), ('Varsity Pictures', -17955723), ('DreamWorks SKG', -21520945), ('Onyx Films', -51893525), ('Studio 37', -51893525), ('Jouror Productions', -51893525), ('Transfilm', -51893525), ('France 2 CinÃ©ma', -82545651)]

# 24. Самый убыточный фильм от Paramount Pictures
Варианты ответа:

1. K-19: The Widowmaker tt0267626
2. Next tt0435705
3. Twisted tt0315297
4. The Love Guru tt0811138
5. The Fighter tt0964517

In [184]:
display(data[data['production_companies'].str.contains(pat='Paramount Pictures')].sort_values(['income']))
answer_ls.append(1)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,income,cast_sep
926,tt0267626,0.722330,100000000,35168966,K-19: The Widowmaker,Harrison Ford|Liam Neeson|Peter Sarsgaard|Joss...,Kathryn Bigelow,Fate has found its hero.,When Russia's first nuclear submarine malfunct...,138,Thriller|Drama|History,Paramount Pictures|Intermedia Films|National G...,7/19/2002,146,6.0,2002,-64831034,"[Harrison Ford, Liam Neeson, Peter Sarsgaard, ..."
1124,tt0300556,1.047214,80000000,19480739,Timeline,Paul Walker|Frances O'Connor|Gerard Butler|Bil...,Richard Donner,They had to travel into the past to save the f...,A group of archaeological students become trap...,116,Action|Adventure|Science Fiction,Paramount Pictures|Donners' Company|Mutual Fil...,11/26/2003,176,5.1,2003,-60519261,"[Paul Walker, Frances O'Connor, Gerard Butler,..."
1723,tt0435705,1.068126,70000000,18211013,Next,Nicolas Cage|Julianne Moore|Jessica Biel|Thoma...,Lee Tamahori,"If you can see the future, you can save it.",Las Vegas showroom magician Cris Johnson has a...,96,Action|Science Fiction|Thriller,Paramount Pictures|Virtual Studios|Revolution ...,4/24/2007,499,5.9,2007,-51788987,"[Nicolas Cage, Julianne Moore, Jessica Biel, T..."
1624,tt0375173,0.898601,60000000,13395939,Alfie,Jude Law|Marisa Tomei|Omar Epps|Jane Krakowski...,Charles Shyer,Meet a man who never met a woman he didn't love.,"In Manhattan, the British limousine driver Alf...",103,Comedy,Paramount Pictures|Patalex Productions,10/22/2004,140,5.4,2004,-46604061,"[Jude Law, Marisa Tomei, Omar Epps, Jane Krako..."
1632,tt0315297,0.767870,50000000,25195000,Twisted,Ashley Judd|Samuel L. Jackson|Andy GarcÃ­a|Dav...,Philip Kaufman,Every murder has a mark.,Recently promoted and transferred to the homic...,97,Action|Adventure|Crime|Drama|Thriller,Paramount Pictures|Kopelson Entertainment|Harl...,2/27/2004,67,5.7,2004,-24805000,"[Ashley Judd, Samuel L. Jackson, Andy GarcÃ­a,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,tt1229238,2.952740,145000000,694713380,Mission: Impossible - Ghost Protocol,Tom Cruise|Jeremy Renner|Simon Pegg|Paula Patt...,Brad Bird,No Plan. No Backup. No Choice.,In the 4th installment of the Mission Impossib...,133,Action|Thriller|Adventure,Paramount Pictures|Skydance Productions|Bad Ro...,12/7/2011,3036,6.7,2011,549713380,"[Tom Cruise, Jeremy Renner, Simon Pegg, Paula ..."
1739,tt0418279,0.890557,150000000,709709780,Transformers,Shia LaBeouf|Josh Duhamel|Megan Fox|Rachael Ta...,Michael Bay,Their war. Our world.,"Young teenager, Sam Witwicky becomes involved ...",144,Adventure|Science Fiction|Action,Paramount Pictures|DreamWorks SKG|Amblin Enter...,6/27/2007,2752,6.6,2007,559709780,"[Shia LaBeouf, Josh Duhamel, Megan Fox, Rachae..."
604,tt0367882,3.161670,185000000,786636033,Indiana Jones and the Kingdom of the Crystal S...,Harrison Ford|Cate Blanchett|Shia LaBeouf|Ray ...,Steven Spielberg,The adventure continues . . .,"Set during the Cold War, the Soviets â€“ led b...",122,Adventure|Action,Lucasfilm|Paramount Pictures,5/21/2008,1537,5.6,2008,601636033,"[Harrison Ford, Cate Blanchett, Shia LaBeouf, ..."
317,tt1055369,0.813323,150000000,836297228,Transformers: Revenge of the Fallen,Shia LaBeouf|Megan Fox|Josh Duhamel|Rainn Wils...,Michael Bay,Revenge is coming,Sam Witwicky leaves the Autobots behind for a ...,150,Science Fiction|Action|Adventure,Paramount Pictures|DreamWorks SKG|Amblin Enter...,6/19/2009,2230,6.0,2009,686297228,"[Shia LaBeouf, Megan Fox, Josh Duhamel, Rainn ..."
829,tt1399103,0.760503,195000000,1123746996,Transformers: Dark of the Moon,Shia LaBeouf|John Malkovich|Ken Jeong|Frances ...,Michael Bay,The invasion we always feared. An enemy we nev...,Sam Witwicky takes his first tenuous steps int...,154,Action|Science Fiction|Adventure,Paramount Pictures|Di Bonaventura Pictures|Has...,6/28/2011,2456,6.1,2011,928746996,"[Shia LaBeouf, John Malkovich, Ken Jeong, Fran..."

# 25. Какой Самый прибыльный год (заработали больше всего)?
Варианты ответа:
1. 2014
2. 2008
3. 2012
4. 2002
5. 2015

In [190]:
data.groupby('release_year')['income'].sum()
answer_ls.append(5)

# 26. Какой Самый прибыльный год для студии Warner Bros?
Варианты ответа:
1. 2014
2. 2008
3. 2012
4. 2010
5. 2015

In [193]:
data[data['production_companies'].str.contains(pat='Warner Bros.')].groupby('release_year')['income'].sum().sort_values()
answer_ls.append(1)

# 27. В каком месяце за все годы суммарно вышло больше всего фильмов?
Варианты ответа:
1. Январь
2. Июнь
3. Декабрь
4. Сентябрь
5. Май

In [208]:
dict_dates = {}
for date in data['release_date']:
    date = date.split('/')[0]
    if date in dict_dates.keys():
        dict_dates[date] += 1
    else:
        dict_dates[date] = 1
print (sorted(dict_dates.items(), key=lambda x: x[1], reverse=False))
answer_ls.append(4)

[('1', 110), ('2', 135), ('5', 140), ('7', 142), ('11', 146), ('6', 147), ('4', 149), ('3', 156), ('8', 161), ('10', 186), ('12', 191), ('9', 227)]

# 28. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)
Варианты ответа:
1. 345
2. 450
3. 478
4. 523
5. 381

In [210]:
count = 0
for date in data['release_date']:
    date = date.split('/')[0]
    if date == '6' or date == '7' or date == '8':
        count += 1
print (count)
answer_ls.append(2)

450

# 29. Какой режисер выпускает (суммарно по годам) больше всего фильмов зимой?
Варианты ответов:
1. Steven Soderbergh
2. Christopher Nolan
3. Clint Eastwood
4. Ridley Scott
5. Peter Jackson

In [212]:
count = {}
for index, row in data.iterrows():
    director = row['director']
    date = row['release_date'].split('/')[0]
    if date == '1' or date == '2' or date == '12':
        if director in count.keys():
            count[director] += 1
        else:
            count[director] =1
print (sorted(count.items(), key=lambda x: x[1], reverse=True))
answer_ls.append(5)

[('Peter Jackson', 7), ('Clint Eastwood', 6), ('Steven Soderbergh', 6), ('Shawn Levy', 4), ('Nancy Meyers', 4), ('Martin Scorsese', 4), ('Adam Shankman', 4), ('Ridley Scott', 3), ('Rob Marshall', 3), ('Tim Burton', 3), ('Patrick Lussier', 3), ('Donald Petrie', 3), ('Marc Lawrence', 3), ('Lasse HallstrÃ¶m', 3), ('Edward Zwick', 3), ('Steven Spielberg', 3), ('Wayne Wang', 3), ('Quentin Tarantino', 2), ('Adam McKay', 2), ('Michael Mann', 2), ('Glenn Ficarra|John Requa', 2), ('Pierre Morel', 2), ('Wes Anderson', 2), ('Paul Thomas Anderson', 2), ('Jaume Collet-Serra', 2), ('George Clooney', 2), ('Shana Feste', 2), ('Ken Kwapis', 2), ('Henry Selick', 2), ('Steve Carr', 2), ('P.J. Hogan', 2), ('David S. Goyer', 2), ('Paul McGuigan', 2), ('Marcus Nispel', 2), ('Andrzej Bartkowiak', 2), ('Scott Cooper', 2), ('Garry Marshall', 2), ('David O. Russell', 2), ('James L. Brooks', 2), ('Brian Levant', 2), ('Martin Campbell', 2), ('Ron Howard', 2), ('Cameron Crowe', 2), ('Dennis Dugan', 2), ('Mark Waters', 2), ('Thomas Carter', 2), ('Bryan Singer', 2), ('Sylvester Stallone', 2), ('Jon M. Chu', 2), ('Gabriele Muccino', 2), ('Andy Tennant', 2), ('David Wain', 2), ('Brad Anderson', 2), ('Gregory Hoblit', 2), ('Jason Friedberg|Aaron Seltzer', 2), ('Simon West', 2), ('Bobby Farrelly|Peter Farrelly', 2), ('Jason Reitman', 2), ('Joe Carnahan', 2), ('Stephen Daldry', 2), ('John Whitesell', 2), ('Spike Jonze', 2), ('Denzel Washington', 2), ('Mark Steven Johnson', 2), ('John Moore', 2), ('Peter Segal', 2), ('Francis Lawrence', 2), ('Rob Reiner', 2), ('Wes Craven', 2), ('Mel Gibson', 2), ('Mike Nichols', 2), ('Joel Schumacher', 2), ('J.J. Abrams', 1), ('Alejandro GonzÃ¡lez IÃ±Ã¡rritu', 1), ('Lana Wachowski|Lilly Wachowski', 1), ('Alex Garland', 1), ('Olivier Megaton', 1), ('Sam Taylor-Johnson', 1), ('Matthew Vaughn', 1), ('Ericson Core', 1), ('David Koepp', 1), ('Sean Anders', 1), ('Ari Sandel', 1), ('Jeremy Garelick', 1), ('Jason Moore', 1), ('Dean Israelite', 1), ('Paul Tibbitt', 1), ('Mike Binder', 1), ('Evan Goldberg|Seth Rogen', 1), ('Phil Lord|Christopher Miller', 1), ('Sergey Bodrov', 1), ('J.C. Chandor', 1), ('Tim Story', 1), ('Kenneth Branagh', 1), ('JosÃ© Padilha', 1), ('Rob Minkoff', 1), ('Angelina Jolie', 1), ('Ava DuVernay', 1), ('Paul W.S. Anderson', 1), ('Will Gluck', 1), ('Stuart Beattie', 1), ('Tom Gormican', 1), ('Akiva Goldsman', 1), ('Russell Crowe', 1), ('Steve Pink', 1), ('Christopher Spencer', 1), ('GrÃ©gory Levasseur', 1), ('Renny Harlin', 1), ('Rupert Wyatt', 1), ('Matt Bettinelli-Olpin|Tyler Gillett', 1), ('James Cameron', 1), ('Patrick Tatopoulos', 1), ('Guy Ritchie', 1), ('Ron Clements|John Musker', 1), ('Jim Sheridan', 1), ('Betty Thomas', 1), ('Gary Winick', 1), ('Michael Spierig|Peter Spierig', 1), ('Antoine Fuqua', 1), ('Rajkumar Hirani', 1), ('NimrÃ³d Antal', 1), ('Tom Tykwer', 1), ('Thor Freudenthal', 1), ('Jonas Elmer', 1), ('Darren Aronofsky', 1), ('Joseph Kosinski', 1), ('Florian Henckel von Donnersmarck', 1), ('Ethan Coen|Joel Coen', 1), ('Paul Weitz', 1), ('Chris Columbus', 1), ('Albert Hughes|Allen Hughes', 1), ('Anand Tucker', 1), ('Rob Letterman', 1), ('Roman Polanski', 1), ('Scott Stewart', 1), ('Kevin Smith', 1), ('Neil Marshall', 1), ('Roger Michell', 1), ('Michael Lembeck', 1), ('Breck Eisner', 1), ('Eric Brevig', 1), ('Tom Vaughan', 1), ('John Erick Dowdle', 1), ('Sngmoo Lee', 1), ('Joel Gallen', 1), ('John A. Davis', 1), ('Peter Howitt', 1), ('Jessie Nelson', 1), ('John Boorman', 1), ("Pat O'Connor", 1), ('Jesse Dylan', 1), ('Frank Darabont', 1), ('Demian Lichtenstein', 1), ('Francine McDougall', 1), ('Doug Liman', 1), ('Roland Emmerich', 1), ('Scott Derrickson', 1), ('Matt Reeves', 1), ('Peyton Reed', 1), ('David Frankel', 1), ('Anne Fletcher', 1), ('Iain Softley', 1), ('Lexi Alexander', 1), ('Pete Travis', 1), ('Martin McDonagh', 1), ('David Moreau|Xavier Palud', 1), ('Frank Miller', 1), ('Sam Mendes', 1), ('Malcolm D. Lee', 1), ('Nicolas Winding Refn', 1), ('Brad Bird', 1), ('David Fincher', 1), ('Ivan Reitman', 1), ('D.J. Caruso', 1), ('Mark Neveldine|Brian Taylor', 1), ('Mikael HÃ¥fstrÃ¶m', 1), ('Greg Mottola', 1), ('Dominic Sena', 1), ('Chris Gorak', 1), ('Christian E. Christiansen', 1), ('Michel Gondry', 1), ('Daniel Barnz', 1), ('Mike Mitchell', 1), ('Kelly Asbury', 1), ('Kevin Macdonald', 1), ('David Gordon Green', 1), ('Alister Grierson', 1), ('Benny Chan', 1), ('Phyllida Lloyd', 1), ('Lee Tamahori', 1), ('Rodrigo GarcÃ\xada', 1), ('Joel Zwick', 1), ('Andrew Davis', 1), ('Stuart Baird', 1), ('Kurt Wimmer', 1), ('Miguel Arteta', 1), ('Jim Gillespie', 1), ('Ron Shelton', 1), ('Nick Cassavetes', 1), ('Michael Rymer', 1), ('Robin Budd|Donovan Cook', 1), ('Dewey Nicks', 1), ('Alexander Payne', 1), ('Mark Pellington', 1), ('Tamra Davis', 1), ('Tom Shadyac', 1), ('Charles Stone III', 1), ('MÃ¥ns MÃ¥rlind|BjÃ¶rn Stein', 1), ('Christopher McQuarrie', 1), ('Michael Sucsy', 1), ('Brad Peyton', 1), ('Tom Hooper', 1), ('Kathryn Bigelow', 1), ('Josh Trank', 1), ('Mike McCoy|Scott Waugh', 1), ('Baltasar KormÃ¡kur', 1), ('Judd Apatow', 1), ('James Watkins', 1), ('Daniel Espinosa', 1), ('Asger Leth', 1), ('Julie Anne Robinson', 1), ('Anthony Hemingway', 1), ('Andy Fickman', 1), ('Steve Trenbirth', 1), ('Todd Phillips', 1), ('David Dobkin', 1), ('John Woo', 1), ('David R. Ellis', 1), ('Anthony Minghella', 1), ('Ronald F. Maxwell', 1), ('Alan Parker', 1), ('Chris Koch', 1), ('Ben Stiller', 1), ('Jonathan Levine', 1), ('Tommy Wirkola', 1), ('Carl Rinsch', 1), ('Peter Berg', 1), ('Harmony Korine', 1), ('Walter Hill', 1), ('Taylor Hackford', 1), ('Ruben Fleischer', 1), ('Seth Gordon', 1), ('John Luessenhop', 1), ('Andy Muschietti', 1), ('Steven Brill|Elizabeth Banks|Steve Carr|Rusty Cundieff|James Duffy|Griffin Dunne|Peter Farrelly|Patrik Forsberg|James Gunn|Brett Ratner|Will Graham|Jonathan van Tulleken', 1), ('Callan Brunker', 1), ('Giuseppe Tornatore', 1), ('Jonathan Teplitzky', 1), ('Allen Hughes', 1), ('Neil Nightingale|Barry Cook', 1), ('Ric Roman Waugh', 1), ('John Wells', 1), ('Christopher B. Landon', 1), ('Ed Gass-Donnelly', 1), ('Justin Chadwick', 1), ('Andrew Adamson', 1), ('James McTeigue', 1), ('Garth Jennings', 1), ('Rob Bowman', 1), ('Cory Edwards|Todd Edwards|Tony Leech', 1), ('John Polson', 1), ('Frederik Du Chau', 1), ('Dean Parisot', 1), ('Louis Leterrier', 1), ('Jean-FranÃ§ois Richet', 1), ('Clare Kilner', 1), ('Geoffrey Sax', 1), ('Uwe Boll', 1), ('Stephen Kay', 1), ('Niki Caro', 1), ('Len Wiseman', 1), ('Frank Marshall', 1), ('James Wong', 1), ('Stefen Fangmeier', 1), ('Robert De Niro', 1), ("Matthew O'Callaghan", 1), ('McG', 1), ('Joe Roth', 1), ('Nick Hurran', 1), ('Aaron Seltzer|Jason Friedberg', 1), ('Bill Condon', 1), ('Chris Noonan', 1), ('Craig Brewer', 1), ('Richard Eyre', 1), ('Wayne Kramer', 1), ('Richard Loncraine', 1), ('Glen Morgan', 1), ('Justin Lin', 1), ('Eric Bress|J. Mackye Gruber', 1), ('Jay Roach', 1), ('Brad Silberling', 1), ('Jeff Schaffer', 1), ('John Hamburg', 1), ('Philip Kaufman', 1), ('Sara Sugarman', 1), ('Guy Ferland', 1), ('Kevin Rodney Sullivan', 1), ('Joseph Kahn', 1), ("Gavin O'Connor", 1), ('Jay Chandrasekhar', 1), ('George Armitage', 1), ('Kevin Allen', 1), ('Jon Turteltaub', 1), ('GÃ¡bor CsupÃ³', 1), ('Tim Hill', 1), ('Chris Weitz', 1), ('Jon Avnet', 1), ('Mennan Yapo', 1), ('Dave Meyers', 1), ('Michael Winterbottom', 1), ('Brian Robbins', 1), ('Richard LaGravenese', 1), ('Jay Russell', 1), ('Jake Kasdan', 1), ('David Leland', 1), ('Peter Webber', 1), ('Tyler Perry', 1), ('Ben Garant', 1), ('Robert Zemeckis', 1), ('Mark Dindal', 1), ('David Twohy', 1), ('Ben Younger', 1), ('Sam Raimi', 1), ('Danny Leiner', 1), ('Brett Ratner', 1), ('Jonathan Lynn', 1), ('Roger Donaldson', 1), ('Danny Boyle', 1), ('John Frankenheimer', 1), ('Gus Van Sant', 1), ('Walter Hill|Jack Sholder', 1), ('Courtney Solomon', 1), ('Diane Keaton', 1)]

# 30. Какой месяц чаще всего по годам самый прибыльный?
Варианты ответа:
1. Январь
2. Июнь
3. Декабрь
4. Сентябрь
5. Май

In [241]:
months = {'1':[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
months['2'] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
months['3'] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
months['4'] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
months['5'] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
months['6'] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
months['7'] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
months['8'] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
months['9'] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
months['10'] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
months['11'] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
months['12'] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

month_income = pd.DataFrame(months, index=[x for x in range (2000, 2016)], columns=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'])
print(month_income['1'][2000])
for index, row in data.iterrows():
    year = row['release_year']
    month = row['release_date'].split('/')[0]
    month_income[month][year] += row['income']
month_income['max'] = month_income.idxmax(axis=1)
month_income['max'].value_counts()
answer_ls.append(2)

0

6     7
12    4
5     4
7     1
Name: max, dtype: int64

# 31. Названия фильмов какой студии в среднем самые длинные по количеству символов?
Варианты ответа:
1. Universal Pictures (Universal)
2. Warner Bros
3. Jim Henson Company, The
4. Paramount Pictures
5. Four By Two Productions

In [250]:
data[data['production_companies'].str.contains(pat='Four By Two Productions')].original_title

1449    Borat: Cultural Learnings of America for Make ...
Name: original_title, dtype: object

In [251]:
dict_studios = {}
for index, studios in data.iterrows():
    length = len(studios['original_title'])
    list_studios = studios['production_companies'].split('|')
    for studio in list_studios:
        if studio in dict_studios.keys():
            dict_studios[studio].append(length)
        else:
            dict_studios[studio] = [length]
dict_studios
stud_length = {}
for studio in dict_studios.keys():
    stud_length[studio] = sum(dict_studios[studio]) / len(dict_studios[studio])
sorted(stud_length.items(), key=lambda x: x[1], reverse=True)
answer_ls.append(5)

# 32. Названия фильмов какой студии в среднем самые длинные по количеству слов?
Варианты ответа:
1. Universal Pictures (Universal)
2. Warner Bros
3. Jim Henson Company, The
4. Paramount Pictures
5. Four By Two Productions

In [255]:
dict_studios = {}
for index, studios in data.iterrows():
    length = len(studios['original_title'].split(' '))
    list_studios = studios['production_companies'].split('|')
    for studio in list_studios:
        if studio in dict_studios.keys():
            dict_studios[studio].append(length)
        else:
            dict_studios[studio] = [length]
dict_studios
stud_length = {}
for studio in dict_studios.keys():
    stud_length[studio] = sum(dict_studios[studio]) / len(dict_studios[studio])
sorted(stud_length.items(), key=lambda x: x[1], reverse=True)
answer_ls.append(5)

# 33. Сколько разных слов используется в названиях фильмов?(без учета регистра)
Варианты ответа:
1. 6540
2. 1002
3. 2461
4. 28304
5. 3432

In [264]:
words = {}
for title in data['original_title'].str.lower():
    title = title.split(' ')
    for word in title:
        if word in words.keys():
            words[word] += 1
        else:
            words[word] = 1
len(words)
answer_ls.append(3)

# 34. Какие фильмы входят в 1 процент лучших по рейтингу?
Варианты ответа:
1. Inside Out, Gone Girl, 12 Years a Slave
2. BloodRayne, The Adventures of Rocky & Bullwinkle
3. The Lord of the Rings: The Return of the King
4. 300, Lucky Number Slevin

In [285]:
data.vote_average.value_counts(bins=100, sort=False)
data[data.vote_average >= 7.956].sort_values(['vote_average'])
display(data[data.original_title == 'Inside Out'])
display(data[data.original_title == 'Gone Girl'])
display(data[data.original_title == '12 Years a Slave'])
display(data[data.original_title == 'The Lord of the Rings: The Return of the King'])
display(data[data.original_title == '300'])
answer_ls.append(1)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,income,cast_sep
9,tt2096673,6.326804,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,Pete Docter,Meet the little voices inside your head.,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/2015,3935,8.0,2015,678708609,"[Amy Poehler, Phyllis Smith, Richard Kind, Bil..."

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,income,cast_sep
128,tt2267998,6.438727,61000000,369330363,Gone Girl,Ben Affleck|Rosamund Pike|Carrie Coon|Neil Pat...,David Fincher,You don't know what you've got 'til it's...,With his wife's disappearance having become th...,145,Mystery|Thriller|Drama,Twentieth Century Fox Film Corporation|Regency...,10/1/2014,3720,7.9,2014,308330363,"[Ben Affleck, Rosamund Pike, Carrie Coon, Neil..."

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,income,cast_sep
1192,tt2024544,3.625529,20000000,187000000,12 Years a Slave,Chiwetel Ejiofor|Michael Fassbender|Lupita Nyo...,Steve McQueen,The extraordinary true story of Solomon Northup,"In the pre-Civil War United States, Solomon No...",134,Drama|History,Plan B Entertainment|Regency Enterprises|River...,10/18/2013,2241,7.9,2013,167000000,"[Chiwetel Ejiofor, Michael Fassbender, Lupita ..."

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,income,cast_sep
1082,tt0167260,7.122455,94000000,1118888979,The Lord of the Rings: The Return of the King,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,The eye of the enemy is moving.,Aragorn is revealed as the heir to the ancient...,201,Adventure|Fantasy|Action,WingNut Films|New Line Cinema,12/1/2003,5636,7.9,2003,1024888979,"[Elijah Wood, Ian McKellen, Viggo Mortensen, L..."

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,income,cast_sep
1683,tt0416449,2.191408,65000000,422610419,300,Gerard Butler|Lena Headey|Dominic West|David W...,Zack Snyder,"Spartans, prepare for glory!","Based on Frank Miller's graphic novel, ""300"" i...",117,Action|Adventure|War,Virtual Studios|Legendary Pictures|Hollywood G...,3/7/2007,3428,7.0,2007,357610419,"[Gerard Butler, Lena Headey, Dominic West, Dav..."

# 35. Какие актеры чаще всего снимаются в одном фильме вместе
Варианты ответа:
1. Johnny Depp & Helena Bonham Carter
2. Hugh Jackman & Ian McKellen
3. Vin Diesel & Paul Walker
4. Adam Sandler & Kevin James
5. Daniel Radcliffe & Rupert Grint

In [287]:
dict_count = {'1': 0, '2':0, '3':0, '4':0, '5':0}
for index, row in data.iterrows():
    if 'Johnny Depp' in row['cast'] and 'Helena Bonham Carter' in row['cast']:
        dict_count['1'] += 1
    if 'Hugh Jackman' in row['cast'] and 'Ian McKellen' in row['cast']:
        dict_count['2'] += 1
    if 'Vin Diesel' in row['cast'] and 'Paul Walker' in row['cast']:
        dict_count['3'] += 1
    if 'Adam Sandler' in row['cast'] and 'Kevin James' in row['cast']:
        dict_count['4'] += 1
    if 'Daniel Radcliffe' in row['cast'] and 'Rupert Grint' in row['cast']:
        dict_count['5'] += 1
dict_count
answer_ls.append(5)

# 36. У какого из режиссеров выше вероятность выпустить фильм в прибыли? (5 баллов)101
Варианты ответа:
1. Quentin Tarantino
2. Steven Soderbergh
3. Robert Rodriguez
4. Christopher Nolan
5. Clint Eastwood

In [290]:
dict_dirs = {'Quentin Tarantino': [0, 0], 'Steven Soderbergh': [0, 0]}
dict_dirs['Robert Rodriguez'] = [0, 0]
dict_dirs['Christopher Nolan'] = [0, 0]
dict_dirs['Clint Eastwood'] = [0, 0]

for index, row in data.iterrows():
    if row['director'] in dict_dirs.keys():
        dict_dirs[row['director']][0] += 1
        if row['income'] > 0:
            dict_dirs[row['director']][1] += 1
dict_dirs
answer_ls.append(4)

# Submission

In [291]:
len(answer_ls)

36

In [292]:
pd.DataFrame({'Id':range(1,len(answer_ls)+1), 'Answer':answer_ls}, columns=['Id', 'Answer'])

    Id  Answer
0    1       4
1    2       2
2    3       3
3    4       2
4    5       1
5    6       5
6    7       2
7    8       1
8    9       4
9   10       5
10  11       3
11  12       1
12  13       3
13  14       4
14  15       5
15  16       1
16  17       3
17  18       3
18  19       2
19  20       1
20  21       4
21  22       2
22  23       3
23  24       1
24  25       5
25  26       1
26  27       4
27  28       2
28  29       5
29  30       2
30  31       5
31  32       5
32  33       3
33  34       1
34  35       5
35  36       4